"use client";
import { useState } from "react";
import { Circle, CheckCircle2, Loader2 } from "lucide-react";

/**
 * InstructionChecklist — fourth of Blueprint's four sub-views (Blueprint
 * design guide §5). The only one with mutable state: parts/wiring/mech
 * are wholesale-regenerated by agents/hardware_speccer.py, but instruction
 * steps get checked off by hand during a build, so this is the one sub-
 * view that round-trips to the backend on every interaction rather than
 * just rendering whatever BlueprintView fetched once.
 *
 * `phases`: device_spec.instructions.phases -- [{id, name, steps: [{id,
 * title, tool_ids, part_ids, done}]}], from GET
 * /api/workspaces/{ws_id}/device-spec's `instructions` slice.
 * `onToggleStep(phaseId, stepId, done)`: expected to call
 * PATCH /api/workspaces/{ws_id}/device-spec/instructions/steps/{step_id}
 * (body: {done}) and resolve once the backend confirms -- this component
 * tracks its own per-step pending state so a slow request doesn't let the
 * user fire the same toggle twice, but does NOT optimistically flip the
 * checkbox itself; it waits for onToggleStep's promise to resolve, then
 * expects the caller to have re-fetched/updated `phases` (same
 * confirm-before-render caution BlueprintView's own wiring already
 * takes -- see the design guide §6 sketch's re-fetch-after-toggle call).
 */
export default function InstructionChecklist({ phases, onToggleStep }) {
  const [pendingStepId, setPendingStepId] = useState(null);

  const totalSteps = phases.reduce((n, ph) => n + ph.steps.length, 0);
  const doneSteps = phases.reduce((n, ph) => n + ph.steps.filter((s) => s.done).length, 0);

  async function handleToggle(phaseId, step) {
    if (pendingStepId) return; // one in-flight toggle at a time
    setPendingStepId(step.id);
    try {
      await onToggleStep(phaseId, step.id, !step.done);
    } finally {
      setPendingStepId(null);
    }
  }

  if (totalSteps === 0) {
    return <p className="text-xs text-[var(--neutral-600)]">No assembly steps generated yet.</p>;
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between text-xs text-[var(--neutral-500)]">
        <span>Instructions</span>
        <span>{doneSteps}/{totalSteps} done</span>
      </div>

      {phases.map((phase) => (
        <div key={phase.id} className="rounded-lg border border-[var(--neutral-800)] p-3 space-y-2">
          <h3 className="text-xs font-medium text-[var(--neutral-200)]">{phase.name}</h3>
          {phase.steps.map((step) => {
            const isPending = pendingStepId === step.id;
            return (
              <button
                key={step.id}
                onClick={() => handleToggle(phase.id, step)}
                disabled={isPending}
                className="w-full flex items-start gap-2 text-left disabled:opacity-60"
              >
                {isPending ? (
                  <Loader2 size={14} className="text-[var(--neutral-500)] mt-0.5 shrink-0 animate-spin" />
                ) : step.done ? (
                  <CheckCircle2 size={14} className="text-green-400 mt-0.5 shrink-0" />
                ) : (
                  <Circle size={14} className="text-[var(--neutral-600)] mt-0.5 shrink-0" />
                )}
                <span className={`text-xs ${step.done ? "text-[var(--neutral-600)] line-through" : "text-[var(--neutral-300)]"}`}>
                  {step.title}
                </span>
              </button>
            );
          })}
        </div>
      ))}
    </div>
  );
}
