"use client";
import { useState } from "react";
import { Circle, CheckCircle2, Loader2, MessageSquareCode } from "lucide-react";

/**
 * InstructionChecklist — fourth of Blueprint's four sub-views (Blueprint
 * design guide §5). The only one with mutable state: parts/wiring/mech
 * are wholesale-regenerated by agents/hardware_speccer.py, but instruction
 * steps get checked off by hand during a build, so this is the one sub-
 * view that round-trips to the backend on every interaction rather than
 * just rendering whatever BlueprintView fetched once.
 *
 * `phases`: device_spec.instructions.phases -- [{id, name, steps: [{id,
 * title, tool_ids, part_ids, done}]}], from GET
 * /api/workspaces/{ws_id}/device-spec's `instructions` slice.
 * `onToggleStep(phaseId, stepId, done)`: expected to call
 * PATCH /api/workspaces/{ws_id}/device-spec/instructions/steps/{step_id}
 * (body: {done}) and resolve once the backend confirms -- this component
 * tracks its own per-step pending state so a slow request doesn't let the
 * user fire the same toggle twice, but does NOT optimistically flip the
 * checkbox itself; it waits for onToggleStep's promise to resolve, then
 * expects the caller to have re-fetched/updated `phases` (same
 * confirm-before-render caution BlueprintView's own wiring already
 * takes -- see the design guide §6 sketch's re-fetch-after-toggle call).
 *
 * `onWorkOnStep(phase, step)` (NEW -- W8.4, optional): when given, every
 * step also gets a "Work on this" button -- BuildTab.jsx's
 * InstructionsView is what turns a click into "open the relevant file in
 * the Editor + pre-fill the chat" (this component knows nothing about
 * either). It's a separate button beside the toggle, not part of it:
 * clicking a step's text still only checks it off. Like onToggleStep it
 * may return a promise; the button shows a spinner and ignores clicks
 * until it settles. Omitted (the default) -> no button, exactly the old
 * checklist.
 */
export default function InstructionChecklist({ phases, onToggleStep, onWorkOnStep = null }) {
  const [pendingStepId, setPendingStepId] = useState(null);
  const [workingStepId, setWorkingStepId] = useState(null); // NEW -- W8.4

  const totalSteps = phases.reduce((n, ph) => n + ph.steps.length, 0);
  const doneSteps = phases.reduce((n, ph) => n + ph.steps.filter((s) => s.done).length, 0);

  async function handleToggle(phaseId, step) {
    if (pendingStepId) return; // one in-flight toggle at a time
    setPendingStepId(step.id);
    try {
      await onToggleStep(phaseId, step.id, !step.done);
    } finally {
      setPendingStepId(null);
    }
  }

  // NEW -- W8.4: independent of pendingStepId on purpose -- toggling a
  // step and working on one are separate requests and shouldn't block
  // each other, only a second click on a Work-on-this that's still going.
  async function handleWorkOn(phase, step) {
    if (workingStepId || !onWorkOnStep) return;
    setWorkingStepId(step.id);
    try {
      await onWorkOnStep(phase, step);
    } finally {
      setWorkingStepId(null);
    }
  }

  if (totalSteps === 0) {
    return <p className="text-xs text-[var(--neutral-600)]">No assembly steps generated yet.</p>;
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between text-xs text-[var(--neutral-500)]">
        <span>Instructions</span>
        <span>{doneSteps}/{totalSteps} done</span>
      </div>

      {phases.map((phase) => (
        <div key={phase.id} className="rounded-lg border border-[var(--neutral-800)] p-3 space-y-2">
          <h3 className="text-xs font-medium text-[var(--neutral-200)]">{phase.name}</h3>
          {phase.steps.map((step) => {
            const isPending = pendingStepId === step.id;
            const isWorking = workingStepId === step.id;
            return (
              // CHANGED -- W8.4: the row is a flex wrapper now so the
              // toggle button and "Work on this" can sit side by side
              // (a <button> inside a <button> isn't valid HTML). The
              // toggle keeps every class it had; `flex-1 min-w-0`
              // replaces `w-full` so it shares the row.
              <div key={step.id} className="flex items-start gap-2">
                <button
                  onClick={() => handleToggle(phase.id, step)}
                  disabled={isPending}
                  className="flex-1 min-w-0 flex items-start gap-2 text-left disabled:opacity-60"
                >
                  {isPending ? (
                    <Loader2 size={14} className="text-[var(--neutral-500)] mt-0.5 shrink-0 animate-spin" />
                  ) : step.done ? (
                    <CheckCircle2 size={14} className="text-green-400 mt-0.5 shrink-0" />
                  ) : (
                    <Circle size={14} className="text-[var(--neutral-600)] mt-0.5 shrink-0" />
                  )}
                  <span className={`text-xs ${step.done ? "text-[var(--neutral-600)] line-through" : "text-[var(--neutral-300)]"}`}>
                    {step.title}
                  </span>
                </button>
                {onWorkOnStep && (
                  <button
                    onClick={() => handleWorkOn(phase, step)}
                    disabled={!!workingStepId}
                    title="Work on this: open the relevant file and start a chat about it"
                    aria-label={`Work on this step: ${step.title}`}
                    className="shrink-0 mt-0.5 flex items-center gap-1 text-[11px] text-[var(--neutral-500)] hover:text-[var(--accent)] disabled:opacity-50"
                  >
                    {isWorking ? <Loader2 size={12} className="animate-spin" /> : <MessageSquareCode size={12} />}
                    <span>Work on this</span>
                  </button>
                )}
              </div>
            );
          })}
        </div>
      ))}
    </div>
  );
}
