"""
eo/chat_store.py — persistent, file-per-chat storage for the UI.

This is deliberately separate from eo/conversation_memory.py:
  - conversation_memory.py / memory/bus.py (Redis) is the AGENTS' short-term
    working memory — capped at MAX_STORED_TURNS, keyed by session_id, used
    to give follow-up prompts recent context.
  - chat_store.py (this file) is the UI's durable, uncapped record of a
    chat: every message, every Working Panel snapshot, chat title, and
    which other chats it's linked to for cross-chat memory sharing. It's
    what gets listed in the sidebar and reloaded after a refresh.

chat_id and session_id are the SAME string everywhere in this system — the
sidebar creates a chat_id, and that value is passed to the existing
session_id parameter on /api/task, eo/executor.py's Pusher channel, and
eo/conversation_memory.py unchanged.
"""
import os
import json
import re
import uuid
import threading
from datetime import datetime, timezone

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHATS_DIR = os.path.join(BASE_DIR, "data", "chats")
INDEX_PATH = os.path.join(CHATS_DIR, "_index.json")

_lock = threading.Lock()  # simple process-wide guard around index read/modify/write


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _ensure_dirs():
    os.makedirs(CHATS_DIR, exist_ok=True)
    if not os.path.exists(INDEX_PATH):
        # NOTE: write the index file directly here rather than calling
        # _write_index() — that function itself calls _ensure_dirs() first,
        # which would recurse back into this branch forever since the file
        # still wouldn't exist yet at the moment of that nested call.
        with open(INDEX_PATH, "w") as f:
            json.dump({"chats": []}, f, indent=2)


def _chat_path(chat_id: str) -> str:
    # chat_id is always generated by this module (see new_chat_id()), so it's
    # already filesystem-safe — this re-check just guards against a
    # hand-crafted id ever being used to escape CHATS_DIR.
    safe = re.sub(r"[^a-zA-Z0-9_\-]", "", chat_id)
    return os.path.join(CHATS_DIR, f"{safe}.json")


def _read_index() -> dict:
    _ensure_dirs()
    with open(INDEX_PATH, "r") as f:
        return json.load(f)


def _write_index(index: dict) -> None:
    _ensure_dirs()
    with open(INDEX_PATH, "w") as f:
        json.dump(index, f, indent=2)


def _clean_tags(tags: list | None) -> list:
    """Strip/dedupe/cap — same defensive shape as chat_workspace.py's name
    truncation. Tags stay free-form strings (no registry, per §0.4's own
    "don't pre-build a tag registry" guidance) but shouldn't be allowed to
    grow unbounded or carry accidental whitespace-only duplicates."""
    if not tags:
        return []
    seen = []
    for t in tags:
        t = (t or "").strip()
        if t and t not in seen:
            seen.append(t)
    return seen[:25]


def new_chat_id() -> str:
    return f"chat_{uuid.uuid4().hex[:12]}"


def create_chat(title: str = "New Chat", tags: list | None = None) -> dict:
    """Creates an empty chat file + index entry. Returns the chat dict."""
    with _lock:
        _ensure_dirs()  # NEW — guards a fresh install with no data/chats/ yet
        chat_id = new_chat_id()
        chat = {
            "id": chat_id,
            "title": title,
            "created_at": _now(),
            "updated_at": _now(),
            "linked_chat_ids": [],
            "tags": _clean_tags(tags),   # NEW — §0.4 unified tagging
            "messages": [],
        }
        with open(_chat_path(chat_id), "w") as f:
            json.dump(chat, f, indent=2)

        index = _read_index()
        index["chats"].insert(0, {
            "id": chat_id,
            "title": title,
            "created_at": chat["created_at"],
            "updated_at": chat["updated_at"],
            "message_count": 0,
            "linked_chat_ids": [],
            "tags": chat["tags"],   # NEW — kept in the index too, so tag
                                     # filtering (list_chats_by_tag below)
                                     # doesn't need to open every chat file.
        })
        _write_index(index)
        return chat


def list_chats() -> list:
    """Sidebar listing — most recently updated first."""
    index = _read_index()
    return sorted(index["chats"], key=lambda c: c["updated_at"], reverse=True)


def list_chats_by_tag(tag: str) -> list:
    """NEW — §0.4. Every chat (any workspace) carrying this exact tag —
    the chat-side half of "tag Q3-launch shows up everywhere at once."
    The node-side half is eo/knowledge_graph.py's search_nodes(tags=[...])
    filter. Reads straight off the index (tags synced there on every
    write below), so this never needs to open individual chat files."""
    return [c for c in list_chats() if tag in (c.get("tags") or [])]


def get_chat(chat_id: str) -> dict:
    path = _chat_path(chat_id)
    if not os.path.exists(path):
        raise FileNotFoundError(f"Unknown chat_id: {chat_id!r}")
    with open(path, "r") as f:
        chat = json.load(f)
    chat.setdefault("tags", [])   # NEW — tolerate chats saved before §0.4
    return chat


def chat_exists(chat_id: str) -> bool:
    return os.path.exists(_chat_path(chat_id))


def set_chat_tags(chat_id: str, tags: list) -> dict:
    """NEW — §0.4. Full replace, same convention as
    eo/workspace_facts.py's set_facts(): the tag editor UI sends the
    whole list back on save. Updates both the chat file and its index
    entry so list_chats_by_tag() stays correct without a rescan."""
    with _lock:
        chat = get_chat(chat_id)
        chat["tags"] = _clean_tags(tags)
        chat["updated_at"] = _now()
        with open(_chat_path(chat_id), "w") as f:
            json.dump(chat, f, indent=2)
        index = _read_index()
        for entry in index["chats"]:
            if entry["id"] == chat_id:
                entry["tags"] = chat["tags"]
                entry["updated_at"] = chat["updated_at"]
        _write_index(index)
        return chat


def append_message(chat_id: str, message: dict) -> dict:
    """Appends one message (shape matches SessionContext.jsx's message
    objects exactly) to the chat file, updates its updated_at, and syncs
    the index's title (auto-titles from the first user message) and
    message_count. Creates the chat if it doesn't exist yet, so the
    frontend can call this immediately after createChat() without a race."""
    with _lock:
        _ensure_dirs()  # NEW — same fresh-install guard as create_chat
        if not chat_exists(chat_id):
            chat = {
                "id": chat_id, "title": "New Chat", "created_at": _now(),
                "updated_at": _now(), "linked_chat_ids": [], "tags": [],
                "messages": [],
            }
        else:
            chat = get_chat(chat_id)

        message = {**message, "ts": message.get("ts") or _now()}
        chat["messages"].append(message)
        chat["updated_at"] = _now()

        # Auto-title: first user message, trimmed, once, so a chat isn't
        # stuck as "New Chat" forever.
        if chat["title"] == "New Chat" and message.get("role") == "user":
            text = (message.get("text") or "").strip().replace("\n", " ")
            if text:
                chat["title"] = text[:60] + ("..." if len(text) > 60 else "")

        with open(_chat_path(chat_id), "w") as f:
            json.dump(chat, f, indent=2)

        index = _read_index()
        found = False
        for entry in index["chats"]:
            if entry["id"] == chat_id:
                entry["title"] = chat["title"]
                entry["updated_at"] = chat["updated_at"]
                entry["message_count"] = len(chat["messages"])
                entry.setdefault("tags", chat.get("tags", []))   # NEW
                found = True
                break
        if not found:
            index["chats"].insert(0, {
                "id": chat_id, "title": chat["title"],
                "created_at": chat["created_at"], "updated_at": chat["updated_at"],
                "message_count": len(chat["messages"]), "linked_chat_ids": [],
                "tags": chat.get("tags", []),   # NEW
            })
        _write_index(index)
        return chat


def rename_chat(chat_id: str, new_title: str) -> dict:
    with _lock:
        chat = get_chat(chat_id)
        chat["title"] = new_title.strip()[:120] or chat["title"]
        chat["updated_at"] = _now()
        with open(_chat_path(chat_id), "w") as f:
            json.dump(chat, f, indent=2)
        index = _read_index()
        for entry in index["chats"]:
            if entry["id"] == chat_id:
                entry["title"] = chat["title"]
                entry["updated_at"] = chat["updated_at"]
        _write_index(index)
        return chat


def set_linked_chats(chat_id: str, linked_chat_ids: list) -> dict:
    """Sets which OTHER chats this chat shares memory with (see §4). One-
    directional by design — linking A -> B does not automatically link
    B -> A, so you decide per chat what feeds INTO it, same as the
    'wiring' the user described."""
    with _lock:
        chat = get_chat(chat_id)
        linked_chat_ids = [c for c in linked_chat_ids if c != chat_id and chat_exists(c)]
        chat["linked_chat_ids"] = linked_chat_ids
        chat["updated_at"] = _now()
        with open(_chat_path(chat_id), "w") as f:
            json.dump(chat, f, indent=2)
        index = _read_index()
        for entry in index["chats"]:
            if entry["id"] == chat_id:
                entry["linked_chat_ids"] = linked_chat_ids
                entry["updated_at"] = chat["updated_at"]
        _write_index(index)
        return chat


def delete_chat(chat_id: str) -> None:
    """Deletes the chat file + index entry, AND clears its Redis working
    memory (eo/conversation_memory.py), so the agents' short-term context
    for this chat_id/session_id is gone too — matches 'deleting it will
    delete the conversations of that chat too.'
    Also strips chat_id out of every OTHER chat's linked_chat_ids, so
    nothing points at a dangling reference."""
    with _lock:
        path = _chat_path(chat_id)
        if os.path.exists(path):
            os.remove(path)
        index = _read_index()
        index["chats"] = [c for c in index["chats"] if c["id"] != chat_id]
        for entry in index["chats"]:
            if chat_id in entry.get("linked_chat_ids", []):
                entry["linked_chat_ids"].remove(chat_id)
        _write_index(index)

    # Clean up any other chat FILES that still reference the deleted one.
    for entry in list_chats():
        if chat_id in entry.get("linked_chat_ids", []):
            other = get_chat(entry["id"])
            other["linked_chat_ids"] = [c for c in other["linked_chat_ids"] if c != chat_id]
            with open(_chat_path(entry["id"]), "w") as f:
                json.dump(other, f, indent=2)

    # Clear the Redis-side short-term memory for this session too.
    try:
        from memory.bus import delete as bus_delete
        bus_delete(f"conversation:{chat_id}")
    except Exception:
        pass  # bus.py needs Upstash env vars; don't let a missing .env break chat deletion


# --- cross-chat memory sharing (§4) --------------------------------------

def _extract_answer_text(message: dict) -> str:
    """Same shape logic as api/task_runner.py's _extract_answer_text, but
    over a stored message dict rather than a live response."""
    data = message.get("data") or {}
    result = data.get("result") or {}
    if "answer" in result:
        return str(result["answer"])
    if "code" in result:
        return str(result["code"])
    if "output" in result:
        return str(result["output"])
    return str(data.get("message") or "")




def get_linked_context_text(chat_id: str, max_turns_per_chat: int = 6,
                             char_limit: int = 400) -> str:
    """Builds a labeled block of recent turns from every chat that
    chat_id links TO (its linked_chat_ids), for injection into the
    agents' context. Returns "" if the chat has no links or doesn't exist
    yet (e.g. a brand new chat_id the frontend hasn't saved to disk yet)."""
    if not chat_exists(chat_id):
        return ""
    chat = get_chat(chat_id)
    linked_ids = chat.get("linked_chat_ids") or []
    if not linked_ids:
        return ""

    blocks = []
    for linked_id in linked_ids:
        if not chat_exists(linked_id):
            continue
        linked = get_chat(linked_id)
        recent = linked["messages"][-max_turns_per_chat:]
        lines = []
        for m in recent:
            if m.get("role") == "user":
                text = m.get("text", "")
            else:
                text = _extract_answer_text(m)
            text = (text or "").strip().replace("\n", " ")
            if len(text) > char_limit:
                text = text[:char_limit] + "..."
            if text:
                lines.append(f"- {m.get('role')}: {text}")
        if lines:
            blocks.append(f"[Shared memory from chat \"{linked['title']}\"]\n" + "\n".join(lines))

    return "\n\n".join(blocks)

def estimate_batch_context_tokens(chat_ids: list, max_turns_per_chat: int = 6,
                                   char_limit: int = 400) -> dict:
    """Rough token-cost estimate for the create-batch modal (§9.2), called
    BEFORE any batch exists. Builds the same labeled block
    get_linked_context_text would build from every OTHER chat in the
    group once they're mutually linked, and estimates tokens with a
    ~4-chars/token heuristic (not a real tokenizer — good enough for a
    "~N tokens" warning, not for billing math).
    Returns a per-chat breakdown plus the worst-case (max) and average
    per-message injection cost, since max is what you actually risk
    hitting once the batch is live."""
    valid_ids = [cid for cid in chat_ids if chat_exists(cid)]
    blocks_by_chat = {}
    for cid in valid_ids:
        chat = get_chat(cid)
        recent = chat["messages"][-max_turns_per_chat:]
        lines = []
        for m in recent:
            text = m.get("text", "") if m.get("role") == "user" else _extract_answer_text(m)
            text = (text or "").strip().replace("\n", " ")
            if len(text) > char_limit:
                text = text[:char_limit] + "..."
            if text:
                lines.append(f"- {m.get('role')}: {text}")
        blocks_by_chat[cid] = (
            f"[Shared memory from chat \"{chat['title']}\"]\n" + "\n".join(lines) if lines else ""
        )

    CHARS_PER_TOKEN = 4
    per_chat_tokens = {}
    for cid in valid_ids:
        others_text = "\n\n".join(
            blocks_by_chat[other] for other in valid_ids if other != cid and blocks_by_chat[other]
        )
        per_chat_tokens[cid] = len(others_text) // CHARS_PER_TOKEN

    values = list(per_chat_tokens.values())
    return {
        "member_count": len(valid_ids),
        "per_chat_tokens": per_chat_tokens,
        "max_tokens_per_message": max(values) if values else 0,
        "avg_tokens_per_message": (sum(values) // len(values)) if values else 0,
    }